---
format:
  html:
    number-sections: false
bibliography: ../references.bib
suppress-bibliography: true
link-citations: true
include-in-header: ../figure/header.html
---

# Elenco dei Test in Italia {.unnumbered}

***PAGINA IN COSTRUZIONE***

Questa pagina tenta di offrire un elenco degli strumenti standarizzati per la valutazione dell’intelligenza attualmente disponibili in Italia nelle loro versioni più recenti. L'elenco è esaustivo e mantenuto aggiornato per quanto possibile (si prega di segnalare a <a href="mailto:enrico.toffalini@unipd.it">enrico.toffalini\@unipd.it</a> eventuali aggiornamenti necessari). Per ogni strumento si elencano informazioni essenziali reperibili da fonti pubbliche (pagine ufficiali, cataloghi editoriali) e, dove possibile, da una consultazione diretta dei manuali. Si offrono inoltre brevi considerazioni teoriche e pratiche su punti di forza e debolezza.


::: {.callout collapse="true"}
## ▶ Note e appunti importanti per la consultazione

- Complessivamente, il panorama italiano è dominato da due case editrici: *Hogrefe* e *Giunti Psychometrics*. 
- Una nota, seria <a href="https://enricotoffalini.github.io/trasparenza-dati-normativi/" target="_blank">diatriba sorta di recente riguarda il crescente uso di scoring online e, cosa più problematica, l'opacità degli algoritmi e la mancata disponibilità dei dati normativi</a> in chiaro sui manuali dei test, politica seguita specialmente da *Giunti Psychometrics* (es. <a href="https://www.rivisteweb.it/doi/10.1449/113146" target="_blank">Frinco et al., 2024</a>; <a href="https://rivisteweb.it/doi/10.1421/116921" target="_blank">Zanon & Priftis, 2025</a>). In questa pagina non ci occuperemo del problema, se non facendo un rimando laddove strettamente necessario. 
- Un limite rilevante di quasi tutti gli strumenti, inclusi quelli che riportano dati normativi in chiaro per la conversione grezzo-ponderato su manuale e/o piattaforma online, è che non riportano comunque statistiche descrittive dettagliate per i punteggi grezzi divisi per fasce di età (specialmente in caso di continuous norming, queste sarebbero necessarie per controllare la bontà delle norme). Essendo un limite di quasi tutti gli strumenti, non lo ripeteremo per ogni caso. 
- L'elenco riporta solo i dettagli essenziali di ogni test, corredati da alcune riflessioni elaborate dalla propria esperienza accademica e dal confronto con esperte e esperti clinici; per ogni ulteriore informazione si può fare riferimento al link pubblico, riportato per ogni strumento. 
- Si è scelto di non riportare un campo "validità psicometrica" per ciascun test (salvo alcuni specifici commento in certi casi), perché un'interpretazione reale e onesta non si può fermare alla considerazione degli indici elaborati dagli editori, ma richiederebbe un approfondito esame e riflessione sui dati, cosa non è ancora stata fatta per tutti i test - tanto più che i dati minimi spesso non sono neppure disponibili (vedi il caso *Giunti Psychometrics* di cui sopra).
- Dove un'informazione si riporta come *"non dichiarata nel link pubblico"* (es. gli anni di pubblicazione di tutti gli strumenti di *Giunti Psychometrics*) si intende verificata a dicembre 2025. 
- Per *"monocomponenziale"* si intende uno strumento che fornisce come solo indice interpretabile una stima del QI generale; per *"multicomponenziale"* si intende uno strumento che fornisce anche indici di componenti specifiche.  
:::

------------------------------------------------------------------------

<!---------IDS-2--------->

<details>

<summary><p style="font-size:25px;">IDS-2 (Intelligence and Development Scales - 2^a^ edizione)</p></summary>
<br/> 
**Link**: <a href="https://www.hogrefe.com/it/shop/intelligence-and-development-scales-2nd-edition.html" target="_blank">https://www.hogrefe.com/it/shop/intelligence-and-development-scales-2nd-edition.html</a>

**Editore**: Hogrefe Italia

**Anno di pubblicazione**: 2022

**Popolazione target**: 5-20 anni

**Numerosità del campione**: 1281 partecipanti

**Continuous norming**: Sì

**Multicomponenziale**: Sì - oltre al QI totale offre indici principali per *Elaborazione visiva*, *Memoria a lungo termine*, *Velocità di elaborazione*, *Memoria fonologica a breve termine*, *Memoria visuo-spaziale a breve termine*, *Ragionamento concettuale*, *Ragionamento verbale*. Oltre alle componenti di intelligenza in senso stretto, valuta anche *Funzioni esecutive*, *Abilità psicomotorie*, *Competenze socio-emozionali*, *Competenze scolastiche*, *Propensione all'impegno*.

**Commento generale**: Interessante strumento multicomponenziale che valuta, oltre all'intelligenza, diversi aspetti dello sviluppo e del funzionamento scolastico. Potenziale valida alternativa alle scale Wechsler per l'età evolutiva. Ispirato esplicitamente al CHC, nonostante non ne copra tutte le aree e tenda a sovra-rappresentare la memoria a breve termine.

**Punti di forza**: 

- Adeguatamente multicomponenziale. 
- Molto utile la struttura per approfondimenti progressivi: QI di screening con 2 subtest (utile per valutazione rapida, ad esempio per sola esclusione disabilità, o per ricerca), QI generale con 7 subtest, QI approfondito con 14 subtest. 
- Apprezzata la possibilità di valutare anche aree diverse dalla sola intelligenza in senso stretto.

**Punti di debolezza**: 

- Sovra-rappresentazione di alcune componenti di competenza cognitiva di base: velocità di elaborazione e memoria (a breve e lungo termine) insieme coprono 4 dei 7 subtest del QI generale; pur essendo aspetti rilevanti delle manifestazioni dell'intelligenza, queste aree non sono necessariamente le più centrali, e potrebbero pesare eccessivamente al ribasso nel caso di valutazioni con condizioni/disturbi del neurosviluppo: si suggerisce, nel caso l'uso di un Indice di Abilità Centrale (<a href="https://doi.org/10.31234/osf.io/b5rh8_v1" target="_blank">Toffalini & Cornoldi, 2025</a>). 
- [richiede approfondimento] La taratura italiana presenta intercorrelazioni tra subtest relativamente modeste, inferiori a quelle del campione internazionale, lasciando qualche dubbio sull'attendibilità psicometrica, specialmente all'interno degli indici.

</details>

------------------------------------------------------------------------

<!---------CFT 20-R--------->

<details>

<summary><p style="font-size:25px;">CFT 20-R (Cattell's Fluid Intelligence Test, Scale 2)</p></summary>
<br/> 
**Link**: <a href="https://www.hogrefe.com/it/shop/cattell-s-fluid-intelligence-test-scale-2.html" target="_blank">https://www.hogrefe.com/it/shop/cattell-s-fluid-intelligence-test-scale-2.html</a>

**Editore**: Hogrefe Italia

**Anno di pubblicazione**: 2019

**Popolazione target**: 8.5-18.11 anni

**Numerosità del campione**: 550 partecipanti

**Continuous norming**: \[da valutare, presumibilmente no\]

**Multicomponenziale**: No - prevede una prova suddivisa in diverse serie di item, ma non fornisce né sarebbe adeguato fornire indici differenziati.

**Commento generale**: Classico test di "intelligenza fluida", basato su materiale interamente non-verbale. Monocomponenziale e di relativamente rapida somministrazione. Avrebbe il potenziale per diventare un efficace e agile test per l'intero arco di vita (in altri paesi presumibilmente lo è già), ma questa edizione in Italia è validata solo per l'età evolutiva, in base a quanto riportato.

**Punti di forza**: 

- Possibilità di somministrazione individuale e collettiva. 
- Relativamente rapida somministrazione (meno di 30 minuti).

**Punti di debolezza**: 

- Non essendo multicomponenziale, non offre ovviamente un profilo esaustivo delle diverse aree di abilità intellettiva.

</details>

------------------------------------------------------------------------

<!---------CFT HR--------->

<details>

<summary><p style="font-size:25px;">CFT-HR (Cattell's Fluid Intelligence Test-Human Resources)</p></summary>
<br/> 
**Link**: <a href="https://www.hogrefe.com/it/shop/cft-hr.html" target="_blank">https://www.hogrefe.com/it/shop/cft-hr.html</a>

**Editore**: Hogrefe Italia

**Anno di pubblicazione**: 2014

**Popolazione target**: 21-66 anni

**Numerosità del campione**: 256 partecipanti

**Continuous norming**: \[da valutare, presumibilmente no\]

**Multicomponenziale**: No - prevede una prova suddivisa in diverse serie di item, ma non fornisce né sarebbe adeguato fornire indici differenziati.

**Commento generale**: Classico test monocomponenziale di intelligenza fluida. Interessante l'esplicito rivolgersi ad applicazioni aziendali di selezione personale. Interamente basato su materiale non-verbale. Di molto rapida somministrazione.

**Punti di forza**: 

- Possibilità di somministrazione individuale e collettiva. 
- Rapida somministrazione (10 minuti nella somministrazione a tempo).

**Punti di debolezza**: 

- Non essendo multicomponenziale, non offre ovviamente un profilo esaustivo delle diverse aree di abilità intellettiva. 
- L'attendibilità psicometrica non è altissima per essere un test di intelligenza (si riporta coerenza interna tra 0.77 e 0.84, ma comunque adeguata e attesa data la somministrazione rapida).

</details>

------------------------------------------------------------------------

<!---------RIAS-2--------->

<details>

<summary><p style="font-size:25px;">RIAS-2 (Reynolds Intellectual Assessment Scales - 2^a^ edizione)</p></summary>
<br/> 
**Link**: <a href="https://www.hogrefe.com/it/shop/reynolds-intellectual-assessment-scales-second-edition.html" target="_blank">https://www.hogrefe.com/it/shop/reynolds-intellectual-assessment-scales-second-edition.html</a>

**Editore**: Hogrefe Italia

**Anno di pubblicazione**: 2021

**Popolazione target**: 3-94 anni

**Numerosità del campione**: 1600 partecipanti

**Continuous norming**: Sì

**Multicomponenziale**: Sì - oltre al QI totale offre indici principali per *Intelligenza verbale*, *Intelligenza non verbale*, *Memoria*, e *Velocità di elaborazione*.

**Commento generale**: Interessante strumento focalizzato sulla stima robusta e agile del QI generale, pensato per mantenere validità anche con disturbi del neurosviluppo o condizioni neuropsicologiche. A uno sguardo distratto la struttura fattoriale può apparire grossolana rispetto a batterie più recenti (la principale suddivisione in intelligenza verbale / non verbale ricorda la struttura delle Wechsler fino alla 3^a^ edizione). Tuttavia, questo rispecchia la scelta teorica di focalizzarsi sugli aspetti centrali del ragionamento e dell'intelligenza, ed è sostenuta dagli autori sulla base di letteratura che evidenzia la scarsa affidabilità psicometrica e utilità empirica di indici per abilità "granulari" e specifiche. RIAS-2 include comunque indici per di memoria e di velocità di elaborazione, specialmente utili per l'assessment clinico, ma li mantiene coerentemente fuori dal calcolo del QI generale. 

**Punti di forza**: 

- Offre stima robusta del QI anche in casi di disturbi del neurosviluppo o condizioni neuropsicologiche. 
- Somministrazione relativamente rapida per il QI (meno di 30 minuti per il solo QI). 
- Copre praticamente l'intero arco di vita con un solo strumento.
- Disponibilità di uno strumento abbreviato (RIST-2) per screening rapido basato su soli 2 subtest. 
- Possibilità di somministrazione da remoto.

**Punti di debolezza**: 

- La multicomponenzialità è meno granulare rispetto ad altri strumenti recenti (ma questo è coerente coi suoi presupposti teorici ed empirici, come detto sopra). 
- Il subtest di Memoria Verbale consiste in ripetizione di frasi, il che potrebbe sommare più processi che la sola memoria: questo potrebbe renderlo meno sensibile ai deficit di processamento fonologico, ma proprio per questo anche meno "utile" a dettagliare il profilo in certi casi (es. dislessia). 

</details>

------------------------------------------------------------------------

<!---------SON-R 2-8--------->

<details>

<summary><p style="font-size:25px;">SON-R 2-8 (Test non verbale di intelligenza Snijders-Oomen, 2-8 anni)</p></summary>
<br/> 
**Link**: <a href="https://www.hogrefe.com/it/shop/test-non-verbale-di-intelligenza-snijders-oomen-2-8-anni.html" target="_blank">https://www.hogrefe.com/it/shop/test-non-verbale-di-intelligenza-snijders-oomen-2-8-anni.html</a>

**Editore**: Hogrefe Italia

**Anno di pubblicazione**: 2024

**Popolazione target**: 2-8 anni

**Numerosità del campione**: 358 partecipanti

**Continuous norming**: \[da valutare, presumibilmente no\]

**Multicomponenziale**: No - i subtest sono raggruppati in prove di ragionamento e prove di performance, ma confluiscono in un unico indice totale.

**Commento generale**: Test non verbale di intelligenza per l'età prescolare e prima età scolare, ideato per ridurre il più possibile l'impatto del linguaggio, adeguato tra gli altri in casi di disturbi di sordità, ipoacusia, disturbo dello spettro autistico, non madrelingua italiani.

**Punti di forza**: 

- Interamente non verbale anche nelle istruzioni. 
- L'offerta di feedback sulla correttezza al bambino dopo ciascun item può essere utile a mantenere la motivazione.

**Punti di debolezza**: 

- Non essendo multicomponenziale, non offre ovviamente un profilo esaustivo delle diverse aree di abilità intellettiva. 
- Il campione è relativamente ridotto rispetto ad altri test (ma d'altro canto anche la fascia di età target è più ristretta). 
- Il tipo di somministrazione e la natura dei compiti potrebbero porre un limite alla complessità raggiunta; lo strumento appare particolarmente adatto a soggetti con difficoltà cognitive o linguistiche, mentre potrebbe risultare meno informativo ai livelli più alti di funzionamento.

</details>

------------------------------------------------------------------------

<!---------CTONI-2--------->

<details>

<summary><p style="font-size:25px;">CTONI-2 (Comprehensive Test of Nonverbal Intelligence - 2^a^ edizione)</p></summary>
<br/> 
**Link**: <a href="https://www.hogrefe.com/it/shop/comprehensive-test-of-nonverbal-intelligence-second-edition.html" target="_blank">https://www.hogrefe.com/it/shop/comprehensive-test-of-nonverbal-intelligence-second-edition.html</a>

**Editore**: Hogrefe Italia

**Anno di pubblicazione**: 2016

**Popolazione target**: 6-16 e 17-99 anni

**Numerosità del campione**: 1100 + 1270 partecipanti

**Continuous norming**: \[da valutare, presumibilmente no\]

**Multicomponenziale**: In misura minima - oltre al QI totale offre indici per 3 abilità di ragionamento: *Ragionamento analogico*, *Ragionamento categoriale*, *Ragionamento sequenziale* (i domini coprono comunque una selezione ristretta).

**Commento generale**: Test non verbale pensato per stimare l’intelligenza generale in bambini e adulti la cui prestazione ai test tradizionali potrebbe essere compromessa da difficoltà linguistiche o motorie specifiche, che dunque si vogliono escludere per una stima più pura del potenziale cognitivo sottostante. Disponibile anche in somministrazione da remoto.

**Punti di forza**: 

- Potenzialmente utilizzabile per l'intero arco di vita (ma presumibilmente più indicato per le fasce basse di funzionamento nell'età adulta). 
- Possibilità di somministrazione da remoto.

**Punti di debolezza**: 

- Non essendo propriamente multicomponenziale, non offre un profilo esaustivo delle diverse aree di abilità intellettiva. 
- [da approfondire] Come altri strumenti non verbali, potrebbe risultare meno sensibile alle differenze ai livelli più alti di funzionamento.

</details>

------------------------------------------------------------------------

<!---------FIT--------->

<details>

<summary><p style="font-size:25px;">FIT (Fluid Intelligence Test)</p></summary>
<br/> 
**Link**: <a href="https://www.hogrefe.com/it/shop/fluid-intelligence-test.html
" target="_blank">https://www.hogrefe.com/it/shop/fluid-intelligence-test.html </a>

**Editore**: Hogrefe Italia

**Anno di pubblicazione**: 2014

**Popolazione target**: 18-57 anni

**Numerosità del campione**: 548 partecipanti

**Continuous norming**: \[da valutare, presumibilmente no\]

**Multicomponenziale**: No

**Commento generale**: Test di intelligenza fluida (Gf) secondo il modello di Carroll, adeguato per buona parte dell'età adulta - per la quale presumibilmente rappresenta l'analogo del *CFT 20-R* (che invece, in Italia, è standardizzato per la sola età evolutiva). Insiste sul rigore psicometrico, effettivamente costruito con modelli IRT che garantiscono buone proprietà. Somministrazione relativamente rapida, sia individuale che collettiva. 

**Punti di forza**: 

- Molto buona attendibilità psicometrica (consistenza interna dichiarata tra 0.93 e 0.99). 
- Tempi di somministrazione abbastanza agili (dichiarano 35 minuti).
- Possibilità di somministrazione collettiva.

**Punti di debolezza**: 

- Non essendo multicomponenziale, non offre ovviamente un profilo esaustivo delle diverse aree di abilità intellettiva. 
- Divisione dei punteggi normativi in 3 fasce d'età potrebbe non avere granularità ideale.
- Forse norme non più perfettamente aggiornate. 

</details>

------------------------------------------------------------------------

<!---------WPPSI-IV--------->

<details>

<summary><p style="font-size:25px;">WPPSI-IV (Wechsler Preschool and Primary Scale of Intelligence - 4^a^ edizione)</p></summary>
<br/> 
**Link**: <a href="https://www.giuntipsy.it/catalogo/test/wppsi-iv-wechsler-preschool-and-primary-scale-of-intelligence-fourth-edition" target="_blank">https://www.giuntipsy.it/catalogo/test/wppsi-iv-wechsler-preschool-and-primary-scale-of-intelligence-fourth-edition </a>

**Editore**: Giunti Psychometrics

**Anno di pubblicazione**: Non dichiarato nel link pubblico - 2019 da manuale

**Popolazione target**: 2.6-7.7 anni

**Numerosità del campione**: 1025 partecipanti (di cui il 20% è campione clinico, e non è chiaro se sia escluso dal contributo alle norme - vedi sotto)

**Continuous norming**: Presumibilmente sì - parla di norme derivate da "modello lineare polinomiale".

**Multicomponenziale**: Sì - oltre al QI totale offre indici principali per *Comprensione verbale*, *Abilità visuospaziali*, *Ragionamento fluido*, *Memoria di lavoro* e *Velocità di elaborazione*. Sono inoltre disponibili indici secondari per *Acquisizione del vocabolario*, *Abilità non verbale*, *Abilità Generale* (IAG),*Competenza cognitiva* (ICC).


**Commento generale**: Classico strumento multicomponenziale per la valutazione dell’intelligenza in età prescolare e nella prima età scolare. La batteria è articolata in due fasce d’età (2.6–3.11 e 4.0–7.7 anni), con differenze nei subtest somministrati e negli indici calcolabili. La struttura segue l’impostazione gerarchica tipica delle scale Wechsler e garantisce continuità concettuale con WISC e WAIS.

**Punti di forza**: 

- Buona copertura delle principali aree cognitive rilevanti per questa fascia d’età: copre un'adeguata selezione di aree del modello CHC, garantendo parsimonia e bilanciamento. 
- Continuità teorica e metodologica con le altre scale Wechsler (stessa struttura della WISC-V), utile per follow-up.

**Punti di debolezza**: 

- Lo scoring online privo di dati normativi in chiaro, combinato all'assenza di statistiche descrittive dettagliate per i dati grezzi (aspetto che riguarda anche molti altri test, purtroppo), rende impossibile un accertamento indipendente e trasparente delle proprietà psicometriche e della bontà dei dati normativi stessi. 
- C'è il dubbio che lo strumento sovrastimi il QI: circa il 20% del campione totale è "clinico" (quindi è sovrarappresentato, e ha funzionamento medio sotto la norma); sebbene esso sia distinto dal campione "normativo", le statistiche descrittive riportate nel manuale per i punteggi ponderati del campione *totale* risultano con media circa 10, che è più di quanto ci si aspetterebbe se il campione clinico non concorresse a definire le norme. 
- La comparabilità longitudinale potrebbe essere limitata tra le due fasce d’età previste dalla batteria (ma è inevitabile a causa dell'applicazione a età molto precoci).

</details>

------------------------------------------------------------------------

<!---------WISC-V--------->

<details>

<summary><p style="font-size:25px;">WISC-V (Wechsler Intelligence Scale for Children - 5^a^ edizione)</p></summary>
<br/> 
**Link**: <a href="https://www.giuntipsy.it/wisc-v-wechsler-intelligence-scale-for-children" target="_blank">https://www.giuntipsy.it/wisc-v-wechsler-intelligence-scale-for-children</a>

**Editore**: Giunti Psychometrics

**Anno di pubblicazione**: Non dichiarato nel link pubblico - 2023 da manuale

**Popolazione target**: 6-17 anni

**Numerosità del campione**: 1500 partecipanti

**Continuous norming**: Sì

**Multicomponenziale**: Sì - oltre al QI totale offre indici principali per *Intelligenza fluida*, *Memoria di lavoro*, *Velocità di elaborazione*, *Abilità visuospaziali*, *Comprensione verbale*. Offre inoltre indici ausiliari per *Ragionamento quantitativo*, *Memoria di lavoro uditiva*, *Abilità non verbale*, *Abilità Generale (IAG)*, *Competenza Cognitiva (ICC)*.

**Commento generale**: Classico strumento multicomponenziale per l'età evolutiva. Migliora la definizione dei fattori rispetto alla precedente WISC-IV (distingue abilità visuospaziale e ragionamento fluido; include un compito di memoria di lavoro visiva). Molto buono il compromesso tra completezza del profilo e parsimonia nella granularità degli indici. Negli anni recenti, in Italia, la WISC-V è diventata il fulcro delle polemiche sulla mancanza di dati normativi in chiaro.

**Punti di forza**: 

- Adeguatamente multicomponenziale: copre una buona selezione di aree del modello CHC, garantendo al contempo parsimonia e bilanciamento. 
- Utile la struttura per approfondimenti progressivi: QI generale con 7 subtest, profilo completo con 10 subtest. Importante la disponibilità di vari indici ausiliari, specialmente IAG e ICC (l'effettiva utilità clinica degli altri andrà approfondita). 
- La stima del QI è particolarmente attendibile. 
- Ampiamente usato a livello internazionale. 

**Punti di debolezza**: 

- Lo scoring online privo di dati normativi in chiaro, combinato all'assenza di statistiche descrittive dettagliate per i dati grezzi (aspetto che riguarda anche molti altri test, purtroppo), rende impossibile un accertamento indipendente e trasparente delle proprietà psicometriche e della bontà dei dati normativi stessi. 
- Il peso dato a memoria di lavoro e velocità di elaborazione nel profilo potrebbe penalizzare casi con condizioni del neurosviluppo o neuropsicologiche (ma il calcolo dell'IAG offre un rimedio).

</details>

------------------------------------------------------------------------

<!---------WAIS-IV--------->

<details>

<summary><p style="font-size:25px;">WAIS-IV (Wechsler Adult Intelligence Scale - 4^a^ edizione)</p></summary>
<br/> 
**Link**: <a href="https://www.giuntipsy.it/catalogo/test/wais-iv-wechsler-adult-intelligence-scale-fourth-edition" target="_blank">https://www.giuntipsy.it/catalogo/test/wais-iv-wechsler-adult-intelligence-scale-fourth-edition</a>

**Editore**: Giunti Psychometrics

**Anno di pubblicazione**: Non dichiarato nel link pubblico - 2013 da manuale

**Popolazione target**: 16-69 anni e 70-90 anni

**Numerosità del campione**: 1424 partecipanti (16–69 anni) + 750 partecipanti (70–90 anni)

**Continuous norming**: No (norme suddivise per classi d'età)

**Multicomponenziale**: Sì - oltre al QI totale offre indici principali per *Comprensione verbale* (ICV), *Ragionamento visuo-percettivo* (IRP), *Memoria di lavoro* (IML) e *Velocità di elaborazione* (IVE). Offre inoltre indici ausiliari per *Abilità Generale (IAG)*, *Competenza Cognitiva (ICC)*.

**Commento generale**: Classico strumento multicomponenziale per l'età adulta e anziana. La struttura fattoriale non è la più aggiornata (vedi WISC-V per confronto; negli Stati Uniti la WAIS-V è già disponibile), ma rimane robusta e adeguata per la maggior parte degli usi clinici e non. Strumento ampiamente validato e conosciuto, specialmente per usi clinici, a livello internazionale. 

**Punti di forza**: 

- Buona copertura dei domini cognitivi più rilevanti (sebbene la suddivisione non sia la più aggiornata). 
- Copre anche l'età avanzata (fino a 90 anni) in modo attendibile.
- La stima del QI è particolarmente attendibile. 

**Punti di debolezza**: 

- Forse norme non più perfettamente aggiornate. 
- Il peso dato a memoria di lavoro e velocità di elaborazione nel profilo potrebbe penalizzare casi con condizioni del neurosviluppo o neuropsicologiche (ma il calcolo dell'IAG offre un rimedio).

</details>

------------------------------------------------------------------------

<!---------Raven's 2--------->

<details>

<summary><p style="font-size:25px;">Raven's 2 (Matrici Progressive di Raven 2)</p></summary>
<br/> 
**Link**: <a href="https://www.giuntipsy.it/matrici-progressive-raven-2" target="_blank">https://www.giuntipsy.it/matrici-progressive-raven-2</a>

**Editore**: Giunti Psychometrics

**Anno di pubblicazione**: Non dichiarato nel link pubblico - 2024 da manuale

**Popolazione target**: 6-90 anni

**Numerosità del campione**: Non dichiarato nel link pubblico - 1293 partecipanti da manuale.

**Continuous norming**: Sì

**Multicomponenziale**: No

**Commento generale**: Versione più recente e integrata delle Matrici Progressive di Raven, che unifica in un'unica batteria le versioni storiche CPM, SPM e APM con item completamente rinnovati e norme aggiornate. Strumento monocomponenziale, interamente non verbale, mirato a stimare rapidamente e con precisione l’abilità cognitiva generale, con particolare enfasi sull'intelligenza fluida. È pensato come test agile e flessibile, utilizzabile in un ampio arco di età e in contesti clinici, educativi e di screening. Il manuale insiste sull'utilizzo dei modelli IRT per stima della difficoltà degli item e dell'abilità del soggetto: le proprietà psicometriche sono, presumibilmente, molto buone.

**Punti di forza**: 

- Ampia copertura dell’arco di vita. 
- Utile anche in presenza di difficoltà linguistiche, disturbi del neurosviluppo o differenze culturali che potrebbero compromettere l’uso di batterie verbali, e modulabile su diversi livelli di abilità. 
- Struttura unificata che semplifica la scelta dello strumento rispetto al "pacchetto" CPM–SPM–APM. 
- Somministrazione relativamente rapida, con possibilità di uso individuale o collettivo e opzioni sia cartacee sia digitali. 

**Punti di debolezza**: 

- Lo scoring online privo di dati normativi in chiaro, combinato all'assenza di statistiche descrittive dettagliate per i dati grezzi (aspetto che riguarda anche molti altri test, purtroppo), rende impossibile un accertamento indipendente e trasparente delle proprietà psicometriche e della bontà dei dati normativi stessi; il manuale non fornisce nemmeno le risposte corrette agli item (il calcolo "manuale" non sarebbe comunque impresa da tentare: il punteggio finale si basa in ogni caso su un algoritmo psicometrico, presumibilmente valido ma comunque opaco). 
- Non essendo multicomponenziale, non offre un vero profilo delle diverse aree di abilità intellettiva e non sostituisce batterie estese (es. Wechsler, IDS-2) quando serve una valutazione articolata. 
- La letteratura indipendente specifica su Raven’s 2, rispetto alle versioni classiche, è per ora inevitabilmente più limitata. 

</details>

------------------------------------------------------------------------

<!---------CPM+SPM+APM--------->

<details>

<summary><p style="font-size:25px;">CPM-SPM-APM (Coloured, Standard, e Advanced Progressive Matrices)</p></summary>
<br/> 
⚠️ La versione più aggiornata attualmente disponibile, che racchiude tutte le versioni in un unico test, è ***Raven's 2*** - vedi sopra.

**Link**:

-   Per CPM: <a href="https://www.giuntipsy.it/cpm" target="_blank">https://www.giuntipsy.it/cpm</a>
-   Per SPM: <a href="https://www.giuntipsy.it/spm-matrici-progressive-di-raven" target="_blank">https://www.giuntipsy.it/spm-matrici-progressive-di-raven</a>
-   Per APM: <a href="https://www.giuntipsy.it/apm" target="_blank">https://www.giuntipsy.it/apm</a>

**Editore**: Giunti Psychometrics

**Anno di pubblicazione**: Non dichiarato nel link pubblico - da 2005 a 2008 da manuale

**Popolazione target**: 3-93 anni (3-11 e 55-93 anni per CPM; 6-60 anni per SPM; 18+ anni per APM)

**Numerosità del campione**: 5263 per CPM; 6283 per SPM; 1766 per APM

**Continuous norming**: Presumibilmente no

**Multicomponenziale**: No

**Commento generale**: Le tre versioni storiche delle Matrici Progressive di Raven (CPM, SPM e APM) costituiscono un classico strumento monocomponenziale per la misura dell'intelligenza non verbale e del ragionamento analogico. Ognuna è pensata per un diverso livello di età e di abilità, dalla prima infanzia (CPM) ai livelli più elevati di funzionamento cognitivo (APM). Lungo decenni di utilizzo, queste forme hanno accumulato una vasta tradizione di impiego in ambito clinico, educativo e di ricerca, rendendole un riferimento importante nello studio di g e dell'intelligenza fluida. ⚠️ Almeno per le finalità cliniche, si devono considerare di fatto sostituite da Raven's 2.

**Punti di forza**: 

- Struttura semplice e interamente non verbale, che riduce il peso del linguaggio (pur non eliminandolo nelle istruzioni) e del background scolastico, rendendo le matrici particolarmente adatte per valutazioni in contesti multiculturali o in presenza di difficoltà linguistiche. 
- Le differenti versioni coprono l’intero arco di sviluppo intellettivo, con CPM più sensibili ai livelli bassi e medi e APM pensate per i livelli più alti di abilità. 
- Le norme italiane, pur non recentissime, si basano su campioni ampi. 
- Ampia tradizione di ricerca.

**Punti di debolezza**: 

- Norme non più aggiornate, con rischio di distorsioni legate all’effetto Flynn e ai cambiamenti socioculturali intercorsi negli anni successivi alla standardizzazione. 
- Mancanza di continuous norming potrebbe limitare la precisione nella stima dei punteggi nelle diverse fasce d’età. 
- Struttura separata in CPM, SPM e APM che richiede una scelta preliminare della forma più adatta e può complicare l’uso (soprattutto in percorsi di valutazione longitudinale). 
- L’ampia diffusione delle matrici e la conoscenza di alcuni item in contesti educativi o training può aumentare il rischio di effetti di pratica. 
- Non essendo multicomponenziali, non offrono un vero profilo delle diverse aree di abilità intellettiva e non sostituiscono batterie estese quando serve una valutazione articolata. 

</details>

------------------------------------------------------------------------

<!---------KBIT-2--------->

<details>

<summary><p style="font-size:25px;">KBIT-2 (Kaufman Brief Intelligence Test - 2^a^ edizione)</p></summary>
<br/> 
**Link**: <a href="https://www.giuntipsy.it/kbit-2" target="_blank">https://www.giuntipsy.it/kbit-2</a>

**Editore**: Giunti Psychometrics

**Anno di pubblicazione**: Non dichiarato nel link pubblico - 2016 da manuale

**Popolazione target**: 4-90 anni

**Numerosità del campione**: 2133 partecipanti

**Continuous norming**: Presumibilmente sì - parla di punteggi standardizzati "elaborati con procedure di smoothing verticale (entro le fasce d'età) e orizzontale (attraverso le fasce di età)".

**Multicomponenziale**: In misura minima - oltre al QI totale offre indici per *QI Verbale* e un *QI Non Verbale* (quest'ultimo in realtà basato sul solo subtest *Matrici*).

**Commento generale**: Strumento rapido per la stima del funzionamento intellettivo generale, utilizzabile su un ampio arco di vita. La struttura è intenzionalmente semplice e orientata a una valutazione rapida, più che a una descrizione articolata del profilo cognitivo. Il QI totale è ottenuto combinando prestazioni verbali e non verbali, con una logica coerente con i test di screening dell’intelligenza, che antepongono agilità e robustezza (che spesso è ciò che serve) a un profilo dettagliato. 

**Punti di forza**: 

- Somministrazione abbastanza rapida (stima del QI entro 30 minuti), il che lo rende utile in diversi contesti (eventualmente anche ricerca) come via di mezzo tra screening e stima robusta. 
- Copertura molto ampia dell’arco di vita.

**Punti di debolezza**: 

- Multicomponenzialità minima: non consente (ma nemmeno è progettato per) un'analisi dettagliata delle diverse componenti cognitive. 

</details>

------------------------------------------------------------------------

<!---------KABC-II--------->

<details>

<summary><p style="font-size:25px;">KABC-II (Kaufman Assessment Battery for Children - 2^a^ edizione)</p></summary>
<br/> 
**Link**: <a href="https://www.giuntipsy.it/kabc-ii" target="_blank">https://www.giuntipsy.it/kabc-ii</a>

**Editore**: Giunti Psychometrics

**Anno di pubblicazione**: Non dichiarato nel link pubblico - 2011 da manuale

**Popolazione target**: 2-19 anni

**Numerosità del campione**: Non dichiarato nel link pubblico, da verificare.

**Continuous norming**: \[da valutare, presumibilmente no\]

**Multicomponenziale**: Sì (sebbene in modo un po' atipico) - offre indici per *Abilità simultanee*, *Abilità sequenziali*, *Pianificazione*, *Apprendimento*, e *Conoscenze*. Non offre un vero "QI totale" ma due scale globali alternative a seconda del modello scelto: *Indice fluido-cristallizzato* (modello CHC, affine al classico QI totale), e *Indice dei processi mentali* (modello di Luria). 

**Commento generale**: Strumento per la misurazione dei processi e delle abilità cognitive in quasi tutta l'età evolutiva. La batteria poggia su una doppia base teorica: modello neuropsicologico di Luria e modello psicometrico CHC, che può orientare l’interpretazione delle prestazioni con o senza l’inclusione delle abilità acquisite. 

**Punti di forza**: 

- Copre un ampio arco evolutivo (2-19 anni). 
- Offre due diverse letture teoriche per interpretare i punteggi. 
- Permette il calcolo di una *Scala non verbale* con somministrazione interamente non verbale, utile per bambini con deficit uditivi, linguistici, di comunicazione verbale, o scarsa padronanza della lingua italiana. 

**Punti di debolezza**: 

- Forse norme non più perfettamente aggiornate. 
- Struttura relativamente complessa, con subtest e indici variabili in base all’età e al modello teorico adottato. 

</details>

------------------------------------------------------------------------

<!---------Leiter-3--------->

<details>

<summary><p style="font-size:25px;">Leiter-3 (Leiter International Performance Scale - 3^a^ edizione)</p></summary>
<br/> 
**Link**: <a href="https://www.giuntipsy.it/leiter-3-test-non-verbale-misura-qi-abilita-cognitive" target="_blank">https://www.giuntipsy.it/leiter-3-test-non-verbale-misura-qi-abilita-cognitive</a>

**Editore**: Giunti Psychometrics

**Anno di pubblicazione**: Non dichiarato nel link pubblico - 2016 da manuale

**Popolazione target**: 3-80 anni

**Numerosità del campione**: 583 partecipanti

**Continuous norming**: No

**Multicomponenziale**: Parzialmente - oltre al *QI non verbale*, che è l'indice principale, offre indici supplementari di *Attenzione* e *Memoria* (non incluse nel calcolo del QI).

**Commento generale**: Test interamente non verbale di intelligenza e abilità cognitive applicabile a un ampio arco di vita. Leiter-3 è progettata per ridurre al minimo l’influenza del linguaggio, sia nei materiali che nelle istruzioni, risultando adatta a persone con difficoltà linguistiche o di comunicazione verbale (per qualsiasi causa). Il QI non verbale rappresenta la misura principale del funzionamento intellettivo generale, affiancata da indici specifici utili soprattutto in ambito clinico e neuropsicologico.

**Punti di forza**: 

- Somministrazione interamente non verbale, anche nelle istruzioni. Ampia copertura dell’arco di vita. 
- Utile in presenza di disturbi del neurosviluppo, deficit linguistici, sordità, scarsa padronanza della lingua o difficoltà motorie. 
- Offre, oltre al QI, informazioni su attenzione e velocità di elaborazione.

**Punti di debolezza**: 

- Multicomponenzialità limitata rispetto a batterie verbali o miste. Il profilo cognitivo risulta meno articolato rispetto a strumenti multicomponenziali completi. 
- Campione normativo relativamente limitato rispetto ad altri test di uso clinico diffuso, specialmente considerata l'assenza di continuous norming. 
- Il tipo di somministrazione potrebbe porre un limite alla complessità raggiunta: l'impressione clinica è che tenda ad andare a soffitto con l'alto funzionamento, rendendo lo strumento probabilmente più adatto ai soli casi con effettive difficoltà.

</details>

------------------------------------------------------------------------
