---
format:
  html:
    number-sections: false
bibliography: ../references.bib
include-in-header: figure/header.html
---

# L'Effetto Flynn {.unnumbered}

## ovvero i risvolti progressisti della ricerca sull'intelligenza {.unnumbered}

### Cos'è l'Effetto Flynn

Pensare al QI ispira spesso riflessioni pessimiste, perché si dice sia molto stabile nel corso della vita (dunque poco "migliorabile") e in larga parte radicato nella genetica. È tutto vero, ma è solo una parte della storia. Il QI, infatti, dice solo come una persona si colloca rispetto alla capacità intellettiva media della sua popolazione di riferimento. Ma cosa ne è della "media"?

Nel corso del Novecento, l'Effetto Flynn ha dimostrato che la capacità di prestazione intellettiva media della popolazione è enormemente plasmabile. Mano a mano che la società innalzava le sue richieste cognitive, richiedendo a masse sempre più ampie di persone di svolgere ruoli sociali e lavorativi sempre più complessi, le persone manifestavano capacità cognitive sempre più complesse, generazione dopo generazione .

E così è avvenuto il miracolo: in un secolo, la prestazione ai test del QI è cresciuta di due deviazioni standard. Vale a dire: la prestazione intellettiva osservata oggi nella media della popolazione è pari a un livello che all'inizio del Novecento era raggiunto solo da una ristretta élite (2-3% delle persone più capaci). È cambiato anche il modo in cui si ragiona: le persone hanno appreso a ragionare in termini sempre più astratti. Oggi però, se la società non fa leva deliberatamente sui fattori che hanno causato l'Effetto Flynn, il beneficio rischia di essere finito, o addirittura capovolto [@flynnSecularChangesIntelligence2020].

### Un cambiamento sociale gigantesco

Un cambiamento così ampio e così rapido non può avere cause genetiche: la genetica di una popolazione non muta in modo rilevante in due o tre generazioni. Le cause sono dunque ambientali, e riguardano tutto ciò che ha reso le società moderne più favorevoli allo sviluppo cognitivo:

-   miglioramento dell’alimentazione e della salute (soprattutto all'inizio, anche miglioramenti semplici nella salute pubblica: introduzione del sale iodato, che favorisce lo sviluppo neurale nei bambini; meno inquinamento da piombo);
-   istruzione di massa e scolarizzazione più lunga;
-   maggiore attenzione data all'educazione di ciascun/a figlio e figlia;
-   diffusione del pensiero astratto in molte situazioni della vita quotidiana e nel lavoro;
-   aumento della complessità delle informazioni e delle tecnologie con cui interagiamo, nella vita quotidiana e nel lavoro.

Curiosamente, le abilità che sono cresciute di più non sono quelle “scolastiche” o basate su conoscenze specifiche, ma quelle astratte e logiche misurate, ad esempio, da test come le Matrici Progressive di Raven. È come se il mondo moderno avesse costretto la mente umana ad allenarsi a pensare in modo "generale", a manipolare sempre di più simboli e concetti astratti rispetto a oggetti concreti.

### Un progresso silenzioso (e forse temporaneo)

L’effetto Flynn ha avuto implicazioni enormi per la psicologia e per la società: ha mostrato che l’ambiente può produrre trasformazioni cognitive profonde ed estese all'intera popolazione, anche se impercettibili nel breve periodo. Come riportato nel brano dello stesso James Flynn tradotto sotto, l'effetto è passato inosservato per gran parte del Novecento ed è stato "scoperto" solo negli anni Ottanta.

Sfortunatamente, negli ultimi decenni questo incremento sembra essersi fermato o addirittura invertito in diversi paesi occidentali, con un primo campanello d'allarme suonato dai paesi scandinavi. Laddove si dispone di dati ampi e rappresentativi su intere coorti (come in Norvegia, dove ogni giovane leva militare viene testata), si sta rilevando una lieve ma costante diminuzione dei punteggi medi di QI da ormai oltre due decenni.

Le cause dell'arresto dell'Effetto Flynn e addirittura del suo possibile declino non sono ben chiare. Una possibilità è che si sia arrivati al "massimo" a cui si poteva arrivare, e semplicemente che non ci sia più margine per ulteriore aumento. Questo è sempre possibile: solo il tempo dirà se davvero non si poteva arrivare "più in alto". L'eventualità del declino, però, suggerisce qualcosa di più articolato. Una recente indagine ha mostrato che l'effetto si osserva *entro* le famiglie [@bratsbergFlynnEffectIts2018], e dunque non sia genetico, ma ancora una volta ambientale: eventualmente dovuto a un deterioramente della qualità degli stimoli intellettuali che provengono dalla società, dalla scuola, dal mondo del lavoro. Questa sembra anche l'interpretazione dello stesso James Flynn, nel brano tradotto sotto.

### Il significato “progressista” dell’Effetto Flynn

L’effetto Flynn è un manifesto ottimista: il funzionamento cognitivo non è fisso e immutabile; il progresso sociale può tradursi in progresso intellettuale. Se è vero che l'intelligenza individuale (QI) è molto radicata nella genetica, la capacità intellettiva dell'intera popolazione è un prodotto della società, e il suo destino dipende da ciò che la società sceglie di valorizzare.

Come attestato dallo stesso Flynn nel brano tradotto sotto, l'evidenza dell'Effetto Flynn ha rovesciato la visione elitaria secondo cui solo una minoranza sarebbe “nata” per svolgere compiti che richiedono pensiero complesso. Ha dimostrato che la mente umana è plastica come neanche gli intellettuali progressisti del Novecento avevano immaginato, e che la crescita collettiva non è solo economica, ma anche cognitiva e morale.

### L'Effetto Flynn secondo lo stesso James Flynn

Il seguente brano è tradotto dall'articolo di @flynnSecularChangesIntelligence2020 intitolato <a href="https://doi.org/10.1017/9781108770422.040" target="_blank">*"Secular changes in intelligence: The Flynn Effect"*</a>:

<em>

::: {style="font-size:50px"}
❝
:::

Fino al 1984, la maggior parte delle persone credeva che il QI medio fosse relativamente stabile nel tempo, almeno nei paesi sviluppati. (...) Prima che venissero documentati enormi miglioramenti del QI, gli studiosi tendevano a valutare l'intelligenza (in seguito chiamata "g" o fattore di intelligenza generale) delle masse popolari in un dato momento e a trarre conclusioni pessimiste. Prima della Prima Guerra Mondiale pochi intellettuali (Bertrand Russell e i marxisti erano eccezioni) pensavano che le masse fossero collettivamente capaci di svolgere quei ruoli sociali cognitivamente complessi che erano prerogativa delle classi superiori.

Molti sostenevano l'istruzione di massa, ma con un feroce pessimismo. Virginia Woolf si riferiva all'operaio autodidatta come a qualcuno che "tutti sapevamo" essere egoista, petulante, grezzo, fastidioso e, in definitiva, nauseante. E. M. Forster non aveva alcuna simpatia per un impiegato i cui tentativi di istruirsi erano "infruttuosi": è semplicemente inferiore alla maggior parte dei ricchi (cioè meno intelligente), com'è tipico dei lavoratori rurali urbanizzati (...)

Durante il ventesimo secolo, quando la società ha aumentato il livello le sue richieste cognitive, il QI medio è aumentato. Nel ventunesimo secolo, se la società ridurrà le richieste, il QI medio diminuirà. Entro certi limiti (non possiamo essere tutti Einstein), la società può ottenere qualsiasi livello di capacità cognitiva sia necessaria allo svolgimento di qualsiasi ruolo decida di assegnare. Ora, la società sta abbassando i propri punteggi di QI a causa di ogni sorta di tendenza che non ha nulla a che fare coi limiti della nostra mente. Se i trend economici favoriscono la disoccupazione di massa e lavori di servizio poco impegnativi a scapito di lavori cognitivamente complessi, se le università istruiscono meno e diventano i parchi giochi di una gioventù edonista, se gli adolescenti trovano intollerabile l'istruzione formale, se le persone leggono di meno e passano il tempo a uccidere marziani su Internet, se il cambiamento climatico distrugge il tessuto sociale, i punteggi finiranno per scendere.

Durante il ventesimo secolo il mercato, semplicemente crescendo, ha fatto cose meravigliose. Ha alleviato la povertà, promosso l'istruzione formale, migliorato le condizioni dei posti di lavoro e liberato le donne; e ha fatto elevare il QI senza nemmeno che ce ne accorgessimo. Ma accontentarsi degli effetti delle richieste del mercato non può risolvere i problemi del ventunesimo secolo. Questi problemi richiedono qualcosa di più che una crescita economica continua, e molto più che un QI elevato. Richiedono quella che Aristotele chiamava "saggezza pratica", uno sforzo collettivo per umanizzare le nostre società con intelligenza critica e conoscenza, e tutto questo ha un costo. L'ignoranza paralizza ogni generazione, non importa quanto alto sia il suo QI medio (...) </em>

\

### Riferimenti bibliografici
